### ISSUE TITLE
Merging repositories

### ISSUE THREAD

**Issue by mutlusun** [Mic92/vicious#17] opened 2016-07-23 14:53 UTC
Hello @Mic92,

what do you think of merging the repositories of you, anrxc (http://git.sysphere.org/vicious/) and me (https://bitbucket.org/mutluyum/vicious_bsd)? Right now I'm maintaining a repository that adds some widgets for BSD users, but I'm a bit unhappy with the situation and would like to merge it into a somewhat more "official" repository. Adrian C. refused to integrate my changes because of lack of time to do this on a regular basis.

How do you like the idea? We would have to contact Adrian C. and ask him as well. Do you know whether he has a Github account?

I suppose that vicious has to be changed a little due to the API changes in awesome 3.6 (even I haven't checked that in detail). Merging would have the advantage of combining efforts and there would be one central point of development. But we would have to find a good solution for compatibility with Linux and BSD.

Thanks!

**Comment by Mic92** [comment] 2016-08-18 05:57
Sorry, for not responding for almost a month.
My repository over the last years was more or less a proxy for people, who don't know how or don't want to send patches via email. I also did some first reviews over the code, so Adrian
merged most of the stuff immediately.  
The problem is, that I also don't want to maintain the FreeBSD Port over a long time either,
because I cannot assure functionality. So for this approach to work
it would be required that you or somebody else would have to commit as a sub maintainer to this port and deal with patches flowing in.
To make the ports maintainable some functions would be required, which can determine the operating system, which then load platform specific implementations to serve information
for widgets. The keys used here should then be also normalized. Conky may provide some ideas how this could be done.

**Comment by mutlusun** [comment] 2016-08-24 09:02
Thanks for your reply.

I would be lucky maintaining the FreeBSD specific code!

As I ported some widgets to FreeBSD, it was really hard to write a Lua function that determines the used platform and calls an appropriate function (see [here](http://lua-users.org/wiki/PlatformDetection)). I decided to write own widgets for each platform, that are separated by an underscore. I think this won't be too much work for an end user.
Indeed, most of the widgets are platform independent so it isn't too much work.

What do you think?

**Comment by psycorama** [comment] 2016-12-13 13:30
Just wanted to bump this. 

I'd like to see the FreeBSD specific code to be easy accessible via github.
So I can share my local changes here, too.

**Comment by Mic92** [comment] 2017-01-28 00:42
fixed

**Closed by Mic92** 2017-01-28 00:42 UTC
