### ISSUE TITLE
Long-running widget workers block user input for some time

### ISSUE THREAD

**Issue by gvlasov** [Mic92/vicious#13] opened 2015-06-05 14:06 UTC
If a worker function in a widget runs for some noticeable time, then user input in X is noticeably blocked for the time the function runs. Particularly that creates problems with the gmail `vicious.widgets.gmail` widget, for an update may take several dozens of milliseconds. Here is a quick and dirty example to demonstrate the problem:

``` lua
-- Test widget that hangs for 1 second every 2 seconds
widget_tbl = {}
function worker(format, warg)
    os.execute("sleep 1")
    answer = {}
    answer[1] = 123
    return answer
end
ioblock = setmetatable(widget_tbl, { __call = function(_, ...) return worker(...) end })
test = wibox.widget.textbox()
vicious.register(
    test,
    ioblock,
    function(widget, args)
        return args[1]
    end,
    2
)
```

If you add this code to your rc, restart awesome and for example start rapidly changing tags in awesome with Mod4+1-2-3, or selecting text in an X application with your mouse, you'll notice input blocking every other second. However, having this widget running does not affect text typing, particularly typing text in X applications' textboxes or working with vim in xterm, — that kind of input doesn't get blocked.

The only solution I see for now is to have updating daemons instead of starting a long-running process each time a widget is executed, and then a widget would just ask those daemons for data. But that seems against the vicious design.

Am I missing something here? Is there any chance this issue is fixed? Are widgets workers supposed to run synchronously by design?

**Comment by Mic92** [comment] 2015-06-06 10:05
Vicious is synchronously by design because of the lack of asynchronous i/o in lua. Personally I don't have any network widgets in my config. I have a mpd widget, which uses luasocket. However the maintainer (anrxc) of vicious didn't want external libraries. If you want to write a non-blocking version of this widget, i will merge it into contribute.

**Comment by mutlusun** [comment] 2017-01-30 12:39
Maybe we can work around this issue by using the new `awful.spawn.easy_async()` function. I assume it is only available since awesome 4.0, but couldn't find an old api documentation. See also [here](https://github.com/copycat-killer/lain/blob/1b428513fdede06ef54679edbfd267534f49659e/helpers.lua#L121).

Drawback: adds a dependency to awful but we have already a dependency to `gears.timer` in `init.lua`.

By the way: does someone know whether vicious runs with the new awesome 4 release? I'm still running 3.6.

**Comment by Mic92** [comment] 2017-01-30 12:58
@mutlusun works without modifications in awesome 4, but there are some deprecation warnings.
At some point we either need to add a compatibility layer for both apis or break with old versions.

**Comment by anrxc** [comment] 2017-03-29 13:27
Yeah this was a common complaint since awesome 2...

The idea was to let people register their own functions with vicious. That way you could have a cron job for long running operations writing the result to the file-system and your function was a simple one-liner reading the file. 

I guess the README could've done a better job suggesting this, but back then it was very common, lots of people made their own widgets with shell scripts from cron, then just read the output.

**Comment by Mic92** [comment] 2017-03-30 16:39
this could be the solution: https://github.com/Mic92/vicious/pull/32

**Comment by Mic92** [comment] 2017-07-14 05:29
pull request is merged now.

**Closed by Mic92** 2017-07-14 05:29 UTC
